import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { generateEnvFile, parseEnv } from './generate-env';

describe('generate-env.ts', () => {
  let logSpy: jest.SpyInstance;
  let warnSpy: jest.SpyInstance;

  beforeEach(() => {
    logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
    warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    logSpy.mockRestore();
    warnSpy.mockRestore();
  });

  it('parseEnv parses keys, strips comments, and handles export prefix', () => {
    const content = [
      '# comment',
      'PLAIN_KEY=value1',
      'export EXPORTED_KEY="value2"',
      'SPACED_KEY = value3',
      '',
    ].join('\n');

    const parsed = parseEnv(content);

    expect(parsed).toEqual({
      PLAIN_KEY: 'value1',
      EXPORTED_KEY: 'value2',
      SPACED_KEY: 'value3',
    });
  });

  it('generateEnvFile writes env.generated.ts with parsed keys', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'generate-env-test-'));
    const envPath = path.join(tempDir, '.env');
    const outPath = path.join(tempDir, 'src', 'env.generated.ts');

    fs.writeFileSync(
      envPath,
      ['REACT_APP_NAME=Qualitick', 'REACT_APP_ENABLE_SIGNUP=true'].join('\n'),
      'utf8'
    );

    const count = generateEnvFile(envPath, outPath);

    expect(count).toBe(2);
    expect(fs.existsSync(outPath)).toBe(true);

    const output = fs.readFileSync(outPath, 'utf8');
    expect(output).toContain('Auto-generated by scripts/generate-env.ts');
    expect(output).toContain('"REACT_APP_NAME": "Qualitick"');
    expect(output).toContain('"REACT_APP_ENABLE_SIGNUP": "true"');
    expect(output).toContain('export default env;');
    expect(logSpy).toHaveBeenCalled();
  });

  it('generateEnvFile writes empty env object when .env is missing', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'generate-env-missing-'));
    const envPath = path.join(tempDir, '.env.missing');
    const outPath = path.join(tempDir, 'src', 'env.generated.ts');

    const count = generateEnvFile(envPath, outPath);

    expect(count).toBe(0);
    expect(warnSpy).toHaveBeenCalled();

    const output = fs.readFileSync(outPath, 'utf8');
    expect(output).toContain('const env = {');
    expect(output).toContain('} as const;');
  });
});
