/*
  Build-time generator: reads .env and outputs src/env.generated.ts
  This lets JS access env values even in bridgeless mode where react-native-config's NativeModule may be empty.
*/
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outDir = path.join(root, 'src');
const outFile = path.join(outDir, 'env.generated.ts');

function parseEnv(content) {
  const lines = content.split(/\r?\n/);
  const obj = {};
  for (const line of lines) {
    if (!line || /^\s*#/.test(line)) continue;
    const match = line.match(/^\s*(?:export\s+|)?([\w\d._-]+)\s*=\s*['"]?(.*?)?['"]?\s*$/);
    if (match && match[1]) {
      obj[match[1]] = (match[2] ?? '').toString();
    }
  }
  return obj;
}

try {
  if (!fs.existsSync(envPath)) {
    console.warn(`[generate-env] No .env found at ${envPath}; writing empty generated file.`);
  }
  const envRaw = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : '';
  const env = parseEnv(envRaw);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const keys = Object.keys(env);
  const lines = [
    '// Auto-generated by scripts/generate-env.js. Do not edit.',
    '/* eslint-disable */',
    'const env = {',
    ...keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(env[k])},`),
    '} as const;',
    'export default env;',
    '',
  ];
  fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
  console.log(`[generate-env] Wrote ${keys.length} keys to ${path.relative(root, outFile)}.`);
} catch (e) {
  console.error('[generate-env] Failed to generate env file:', e);
  process.exit(1);
}
