/*
  Build-time generator: reads .env and outputs src/env.generated.ts
  This lets JS access env values even in bridgeless mode where react-native-config's NativeModule may be empty.
*/
import fs from 'node:fs';
import path from 'node:path';

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outDir = path.join(root, 'src');
const outFile = path.join(outDir, 'env.generated.ts');

function parseEnv(content: string): Record<string, string> {
  const lines = content.split(/\r?\n/);
  const obj: Record<string, string> = {};
  for (const line of lines) {
    if (!line || /^\s*#/.test(line)) continue;
    const match = line.match(/^\s*(?:export\s+|)?([\w\d._-]+)\s*=\s*['"]?(.*?)?['"]?\s*$/);
    if (match && match[1]) {
      obj[match[1]] = (match[2] ?? '').toString();
    }
  }
  return obj;
}

export function generateEnvFile(envFilePath: string = envPath, outputFilePath: string = outFile): number {
  if (!fs.existsSync(envFilePath)) {
    console.warn(`[generate-env] No .env found at ${envFilePath}; writing empty generated file.`);
  }

  const envRaw = fs.existsSync(envFilePath) ? fs.readFileSync(envFilePath, 'utf8') : '';
  const env = parseEnv(envRaw);

  const outputDir = path.dirname(outputFilePath);
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const keys = Object.keys(env);
  const lines = [
    '// Auto-generated by scripts/generate-env.ts. Do not edit.',
    '/* eslint-disable */',
    'const env = {',
    ...keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(env[k])},`),
    '} as const;',
    'export default env;',
    '',
  ];

  fs.writeFileSync(outputFilePath, lines.join('\n'), 'utf8');
  console.log(`[generate-env] Wrote ${keys.length} keys to ${path.relative(root, outputFilePath)}.`);
  return keys.length;
}

export { parseEnv };

if (typeof require !== 'undefined' && require.main === module) {
  try {
    generateEnvFile();
  } catch (e) {
    console.error('[generate-env] Failed to generate env file:', e);
    process.exit(1);
  }
}
